### ISSUE TITLE
yaml_parser

### ISSUE THREAD

**Issue by igorpodolak** [Lamiane/DCN#1]
## Yaml parser
The yaml parser looks ok, but there are some issues simple to:
1. the `__init__()` function should be called with arguments; the best would be `__init__(self, **kwargs)`, i.e. with a dictionary of available fields. Then it would be possible, while constructing a more complicated network structure, to have a `dict()` with options, modified all from layer to layer and from yaml to yaml, with different options and then used like in `yaml_parser_tests.py` file?

**Comment by igorpodolak** [comment]
2. Actually, to construct new yamls, e.g. for each fold, the substitution with `yaml % param_dict` needs to be done **twice**: first to construct the model, and then to substitute concrete values for some of the variables like `num_channels`. If one sets `space.num_channels = "%(num_channels)i"` in the `MLP` description, then the first run constructs

'num_channels: '%(num_channels)i'` 

instead of

`num_channels: %(num_channels)i`

and the second run of format results in `num_channels: '1'`
which is interpreted as a string, instead of an integer...
That is strings are processed incorrectly in `parse_to_yaml()`: they are treated with `__repr__()` but should be processed with `__str__()`.

**Comment by Lamiane** [comment]
not an issue anymore.
